### PR TITLE
Mouse events

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by Berstad** [comment]
Seems to work well, mouse tracking works, however the following error comes up on windows when clicking:

> Traceback (most recent call last):
>   File "_ctypes/callbacks.c", line 234, in 'calling callback function'
>   File "C:\Program Files\Python35\lib\site-packages\pyglet\window\win32\__init__.py", line 617, in f
>     result = event_handler(msg, wParam, lParam)
>   File "C:\Program Files\Python35\lib\site-packages\pyglet\window\win32\__init__.py", line 767, in _event_mousemove
>     x, y, dx, dy, buttons, modifiers)
>   File "C:\Program Files\Python35\lib\site-packages\pyglet\window\__init__.py", line 1154, in dispatch_event
>     if EventDispatcher.dispatch_event(self, *args) != False:
>   File "C:\Program Files\Python35\lib\site-packages\pyglet\event.py", line 355, in dispatch_event
>     if handler(*args):
>   File "C:/Users/TorJan/PycharmProjects/sim_game/src/main.py", line 58, in on_mouse_drag
>     game.mouse_drag(x, y, dx, dy, get_button(button), modifiers)
> NameError: name 'button' is not defined

**Comment by olehermanse** [comment]
> File "C:/Users/TorJan/PycharmProjects/sim_game/src/main.py", line 58, in on_mouse_drag
game.mouse_drag(x, y, dx, dy, get_button(button), modifiers)

Doesn't match what's in this commit (see Files Changed). Maybe this branch was updated after you downloaded it. Try force pulling, or resetting/deleting the local branch before pulling again. Any of these should work:
```
git checkout mouse
git pull -f
```
```
git checkout mouse
git reset HEAD~5
git pull
```
```
git checkout master
git branch -D mouse
git checkout -b mouse
git fetch
git rebase origin/mouse
```

**Review by Berstad — COMMENTED** [review]
Seems to be working well

**Review by Berstad — APPROVED** [review]
See previous comment

**Pull request merged**
